# Generated by Django 3.0.6 on 2020-05-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fees',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
