# Generated by Django 3.0.6 on 2020-05-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fees',
            field=models.CharField(default='Unpaid', max_length=30),
        ),
    ]
